name: emdad_khodro_saipa
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  crypto: ^3.0.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^3.0.1
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flip_card: ^0.6.0
  flutter_neumorphic: ^3.2.0
  google_maps_flutter: ^2.1.4
  http: ^0.13.4
  intl: ^0.17.0
  mapir_raster: ^0.0.1
  local_auth: ^2.0.1
  location: ^4.4.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.2
  permission_handler: ^8.2.5
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.4.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.2
  carousel_indicator: ^1.0.6


dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/strings/en.json
    - assets/strings/fa.json
    - assets/images/


  fonts:
#    - family: Iranian
#      fonts:
#        - asset: assets/fonts/Iranian-Sans.ttf

    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
